spring:
  application:
    name: jenjetsu-cdr
    enable-auto-collect: false

phone-number-generator:
  pattern: 79#########

CallInfoCreator:
  min-call-duration-seconds: 10
  max-call-duration-seconds: 180
  min-call-date: 2023-01-01
  max-call-date: 2023-12-31
  min-phone-calls: 3
  max-phone-calls: 18