server:
  port: 8100

spring:
  application:
    name: jenjetsu-cdr
    enable-auto-collect: ${SPRING_APPLICATION_ENABLE-AUTO-COLLECT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE}

phone-number-generator:
  pattern: ${PHONE-NUMBER-GENERATOR_PATTERN}

CallInfoCreator:
  min-call-duration-seconds: ${CALLINFOCREATOR_MIN-CALL-DURATION-SECONDS}
  max-call-duration-seconds: ${CALLINFOCREATOR_MAX-CALL-DURATION-SECONDS}
  min-call-date: ${CALLINFOCREATOR_MIN-CALL-DATE}
  max-call-date: ${CALLINFOCREATOR_MAX-CALL-DATE}
  min-phone-calls: ${CALLINFOCREATOR_MIN-PHONE-CALLS}
  max-phone-calls: ${CALLINFOCREATOR_MAX-PHONE-CALLS}