server:
  port: 8100

spring:
  application:
    name: jenjetsu-cdr
    enable-auto-collect: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

phone-number-generator:
  pattern: 79#########

CallInfoCreator:
  min-call-duration-seconds: 10
  max-call-duration-seconds: 1800
  min-call-date: "2023-01-01"
  max-call-date: "2023-12-31"
  min-phone-calls: 5
  max-phone-calls: 15