server:
  port: 8888

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: jenjetsu-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties
  profiles:
    default: native

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

encrypt:
  key: 0xx9aG7EuIUNLNBHAwuT9TVe8HKY7RHF