server:
  port: 8888

spring:
  application:
    name: jenjetsu-config
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/IdeaProjects/jenjetsu-module-application/jenjetsu-config/src/main/resources/properties
  profiles:
    default: native