server:
  port: 8761

spring:
  application:
    name: Eureka-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost