server:
  port: 8080

spring:
  application:
    name: BRT
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  minio:
    access-key: Rl0oO5YUFKMD32JrlQGP
    secret-key: my5xxN1yL9NK61opuOyIvC9yHbIeUG2WCbDPZFQh
    bucket-name: trash
    secure: false
    url: http://localhost:9000
  rabbitmq:
    host: localhost
    username: rmuser
    password: rmpassword
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5001/brt_database?characterEncoding=utf8"
    username: Stey
    password: 1228
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka